'''
Add the **moeda.py** module created in the previous challenges, 
along with a function called **summary()**, which displays on the screen some information 
generated by the functions we already have in the module created so far.

'''

import moeda

p = float(input('Digite o preço: R$ '))
moeda.resumo(p, 10, 5)