pessoa = ('Evander', 38, 'M', 108.65) #POSSO DEFINIR TEXTOS E NÚMEROS JUNTOS NAS TUPLAS
#del(pessoa) #COMO A TUPLA É IMUTÁVEL, ESSE COMANDO PERMITE APENAS DELETAR A TUPLA POR COMPLETO.
#EX: del(pessoas[0]) DARÁ UM ERRO, POIS NÃO É POSSIVEL DELETAR UM VALOR DA TUPLA.
print(pessoa)